### ISSUE TITLE
无法正确解析katex公式

### ISSUE THREAD

**Issue by halftop** [Suremotoo/gridea-theme-nederburg#1]
比如` $\to$ `正确解析之后是一个向右的箭头，官方的paper主题可以正确解析，而本主题就会解析错误

**Comment by Suremotoo** [comment]
由于工作原因，很抱歉今天才回复。这个应该和Gridea中Markdown的渲染有关，作者会在下个版本中修复这个问题。

**Comment by EryouHao** [comment]
@Suremotoo Katex 解析，需要在主题中引入单独的 js 和 font 来渲染

**Comment by Suremotoo** [comment]
了解，这边后续尝试加上！

**Comment by Suremotoo** [comment]
@halftop  已经添加上 katex 的渲染。

**Comment by halftop** [comment]
![image](https://user-images.githubusercontent.com/30852770/57231136-843e1f80-704c-11e9-8206-d6dcb2a65957.png)
解析有错误啊，幂本应是上标，怎么变下表了。

**Comment by Suremotoo** [comment]
这个作者在下个Gridea版本会修复（我已经测试最新版此问题已经解决了哟😜😜），耐心等待下个版本。
